//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab_29.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_MovieS
    {
        public string Movie_Name { get; set; }
        public string Description { get; set; }
        public string Year { get; set; }
        public decimal Rating { get; set; }
        public System.TimeSpan Running_Time { get; set; }
        public int Movie_ID { get; set; }
    }
}
